import Foundation

extension Bundle {
    /// Safe lookup that avoids the fatal trap in the autogenerated `Bundle.module`
    /// when the resource bundle is not placed at the expected path in a packaged app.
    static let trimmyCoreSafeBundle: Bundle = {
        // 1. Try the autogenerated module bundle (works in dev / swift test)
        let moduleName = "Trimmy_TrimmyCore"
        if let url = Bundle.main.url(forResource: moduleName, withExtension: "bundle"),
           let bundle = Bundle(url: url)
        {
            return bundle
        }

        // 2. Try next to the main bundle (packaged app layout)
        let rootURL = Bundle.main.bundleURL
            .appendingPathComponent("Contents/Resources/\(moduleName).bundle")
        if let bundle = Bundle(url: rootURL) {
            return bundle
        }

        // 3. Fallback: try the autogenerated .module (may fatal if not found)
        return .module
    }()
}
